#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
##############################################################################

# Set VIRTUALENVWRAPPER_PYTHON to the path of the Python executable that
# virtualenv is installed under before sourcing this script. Otherwise,
# the next line will default to /user/bin/python, which is not what you
# want if you're using something like Homebrew that puts Python in
# /usr/local/bin.
if [[ -f /usr/local/bin/python ]]; then
    export VIRTUALENVWRAPPER_PYTHON="/usr/local/bin/python"
else
    export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python"
fi

export DEFAULT_USER='dale'
export HOSTNAME=`hostname -s`
export PROJECT_HOME="$HOME/Source"
export SCRIPTS="$HOME/Dropbox/Scripts"
export HOMEBREW_EDITOR=/usr/local/bin/mate

if [[ -d $HOME/Tools ]]; then
    # HandBrakeCLI, git-submodule-move etc.
    export PATH=$HOME/Tools:$PATH
fi

if [[ "$OSTYPE" == darwin* ]]; then
    # Amend Python path for Homebrew PyQt
    export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
    # Node path
    export NODE_PATH=/usr/local/lib/node
    export PATH=/usr/local/share/npm/bin:$PATH
    # Put brew commands ahead of system-provided commands
    export PATH=/usr/local/bin:/usr/local/sbin:$PATH
    # Java location
    export JAVA_HOME=$(/usr/libexec/java_home)

    if [[ $HOSTNAME:l == "retina-pro" ]]; then
        # Moscow SML 2.10
        export PATH=/Users/dale/Tools/mosml2.10/bin:$PATH
        # MAME
        export PATH=/Users/dale/Tools/mame0148-64bit:$PATH
        # Android SDK
        export ANDROID_SDK_ROOT=/usr/local/opt/android-sdk
        # CUDA - Homebrew will complain about DYLD_LIBRARY_PATH being set
        # export DYLD\_LIBRARY\_PATH=/usr/local/cuda/lib:\$DYLD\_LIBRARY\_PATH
        # GUAPDF - Uncomment the CUDA lib path above for GPU-optimized version

        # ImageOptim-CLI
        export PATH=/Users/dale/Source/_github/ImageOptim-CLI/bin:$PATH

    elif [[ $HOSTNAME:l == "dale-mac-lt" ]]; then
        export PATH="$(brew --prefix homebrew/php/php53)/bin:$PATH"
    fi
    # Qt 5.4.0
    export PATH=/Users/dale/Tools/Qt5.4.0/5.4.0/clang_64/bin:$PATH
fi
